### ISSUE TITLE
Pll Requestをどうやって出すのだろうか。。わからん。

### ISSUE THREAD

**Issue by tsuchiya-fido** [aikimatsu/TestRepo#4]

**Comment by aikimatsu** [comment]
<img width="529" alt="capturfiles-mar-07-2018_06 32 35" src="https://user-images.githubusercontent.com/10862098/37097968-90dd1626-21d1-11e8-816c-41424e0b7076.png">
新しいブランチを作成して、ファイルに変更を加えた後でPull Requestを作成する形になります。

**Comment by tsuchiya-fido** [comment]
Me
